- hosts: consul
  become: yes
  roles:
    - role: consul
      vars:
        dc_name: "sirius"
        consul_ansible_group: "consul"

- name: psql
  hosts: postgres
  become: true
  strategy: linear
  roles:
    - client
